"""Provider-neutral model contracts and deterministic routing helpers."""

from __future__ import annotations

import asyncio
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any, Protocol

from pydantic import BaseModel, ConfigDict, Field, ValidationError


class ChatMessage(BaseModel):
    """Provider-neutral chat message sent to a model client.

    Attributes:
        role: Conversation role understood by the provider adapter.
        content: Text content for the message.
    """

    role: str
    content: str


class GenerationOptions(BaseModel):
    """Validated generation settings passed to a provider for one call.

    Attributes:
        model: Provider-native model identifier from the resolved registration.
        temperature: Sampling temperature.
        max_tokens: Optional positive output-token limit.
        timeout: Optional positive timeout in seconds for each attempt.
        retries: Number of safe retry attempts after the initial request.
    """

    model: str
    temperature: float = 0.0
    max_tokens: int | None = Field(default=None, gt=0)
    timeout: float | None = Field(default=None, gt=0)
    retries: int = Field(default=0, ge=0)


@dataclass(frozen=True)
class StructuredOutputRequest:
    """Named JSON schema that a provider must satisfy natively."""

    name: str
    schema: dict[str, Any]

    def __init__(
        self,
        name: str,
        schema: dict[str, Any] | None = None,
        *,
        json_schema: dict[str, Any] | None = None,
    ) -> None:
        resolved_schema = schema if schema is not None else json_schema
        if resolved_schema is None:
            raise ValueError("StructuredOutputRequest requires 'schema' or 'json_schema'")
        object.__setattr__(self, "name", name)
        object.__setattr__(self, "schema", resolved_schema)

    @property
    def json_schema(self) -> dict[str, Any]:
        return self.schema


class Usage(BaseModel):
    """Provider-neutral token usage counters.

    Attributes:
        input_tokens: Tokens consumed by request input.
        output_tokens: Tokens generated by the provider.
        total_tokens: Total tokens reported for the request.
    """

    input_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    total_tokens: int = Field(default=0, ge=0)


class ProviderResult(BaseModel):
    """Normalized completion result returned by a model provider.

    Attributes:
        content: Optional unstructured text response.
        structured: Optional decoded structured response.
        usage: Provider-neutral usage counters.
        accepted: Whether the provider accepted the request. Accepted failures
            are not automatically retried.
        request_id: Optional non-secret provider request identifier.
    """

    content: str | None = None
    structured: dict[str, Any] | None = None
    usage: Usage = Field(default_factory=Usage)
    accepted: bool = False
    request_id: str | None = None


@dataclass(frozen=True, slots=True)
class ProviderCapabilities:
    """Capabilities advertised by a registered provider client.

    Attributes:
        structured_output: Supports native schema-constrained output.
        tool_calling: Supports provider-native tool calls.
        context_limit: Maximum advertised context size, or zero when unknown.
        usage_reporting: Returns token usage with results.
    """

    structured_output: bool = False
    tool_calling: bool = False
    context_limit: int = 0
    usage_reporting: bool = False


class ProviderError(RuntimeError):
    """Base provider error with explicit retry and acceptance state."""

    def __init__(
        self,
        message: str,
        *,
        retryable: bool = False,
        accepted: bool = False,
    ) -> None:
        super().__init__(message)
        self.retryable = retryable and not accepted
        self.accepted = accepted


class ProviderAuthenticationError(ProviderError):
    """Provider rejected or could not get authentication."""


class ProviderRateLimitError(ProviderError):
    def __init__(
        self,
        message: str = "Provider rate limit exceeded",
        *,
        accepted: bool = False,
    ) -> None:
        super().__init__(message, retryable=True, accepted=accepted)


class ProviderContentPolicyError(ProviderError):
    """Provider rejected content under its safety or usage policy."""


class ProviderTimeoutError(ProviderError):
    def __init__(
        self,
        message: str = "Provider request timed out",
        *,
        accepted: bool = False,
    ) -> None:
        super().__init__(message, retryable=True, accepted=accepted)


class UnsupportedProviderCapabilityError(ProviderError):
    """Provider cannot satisfy a capability required by the request."""


class MalformedStructuredOutputError(ProviderError):
    """Provider output did not satisfy the required structured contract."""


class ModelProvider(Protocol):
    """Protocol implemented by credential-bearing model clients.

    Implementations are registered with a runtime-owned provider registry.
    Agents and run requests reference them indirectly and never retain their
    credentials or provider-specific configuration.
    """

    capabilities: ProviderCapabilities

    async def complete(
        self,
        messages: Sequence[ChatMessage],
        *,
        options: GenerationOptions,
        structured_output: StructuredOutputRequest,
    ) -> ProviderResult: ...


def build_routing_schema(
    routing_metadata: Sequence[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Return the constrained selection schema used for model routing."""
    schema = RoutingSelection.model_json_schema()
    if routing_metadata is not None:
        branches: list[dict[str, Any]] = []
        for entry in routing_metadata:
            agent_id = entry.get("name")
            if not agent_id:
                continue
            capability_ids = sorted(
                {
                    str(capability_id)
                    for capability in entry.get("capabilities", [])
                    for capability_id in (
                        capability.get("id"),
                        capability.get("name"),
                    )
                    if capability_id
                }
            )
            if not capability_ids:
                continue
            branches.append(
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "agent_id": {"const": str(agent_id)},
                        "capability_id": {"enum": capability_ids},
                        "arguments": {"type": "object"},
                    },
                    "required": ["agent_id", "capability_id"],
                }
            )
        schema = {"oneOf": branches}
    return schema


class RoutingSelection(BaseModel):
    """Strict structured capability selection accepted by the orchestrator.

    Attributes:
        agent_id: Published identifier of the selected agent.
        capability_id: Capability name or generated skill identifier.
        arguments: Structured arguments for the selected capability.
    """

    model_config = ConfigDict(extra="forbid")
    agent_id: str = Field(min_length=1)
    capability_id: str = Field(min_length=1)
    arguments: dict[str, Any] = Field(default_factory=dict)


class ModelConfiguration(BaseModel):
    """Immutable provider-neutral model configuration.

    The configuration identifies a provider and its provider model name, plus
    safe request defaults. Credentials, authorization headers, and other
    sensitive provider settings must remain inside the registered client.
    """

    provider: str = Field(min_length=1)
    model: str = Field(min_length=1)
    endpoint: str | None = None
    timeout: float = Field(default=30.0, gt=0)
    retries: int = Field(default=0, ge=0)

    model_config = ConfigDict(extra="forbid", frozen=True)


class FakeModel:
    """Deterministic provider for unit and acceptance tests."""

    capabilities = ProviderCapabilities(
        structured_output=True,
        tool_calling=False,
        context_limit=128_000,
        usage_reporting=True,
    )

    def __init__(
        self,
        selection: RoutingSelection | dict[str, Any] | str,
        *,
        usage: Usage | None = None,
        accepted: bool = True,
    ) -> None:
        self.selection = selection
        self.usage = usage or Usage()
        self.accepted = accepted
        self.calls = 0

    async def complete(
        self,
        messages: Sequence[ChatMessage],
        *,
        options: GenerationOptions,
        structured_output: StructuredOutputRequest,
    ) -> ProviderResult:
        _ = (messages, options, structured_output)
        self.calls += 1
        if isinstance(self.selection, str):
            return ProviderResult(content=self.selection, usage=self.usage, accepted=self.accepted)
        selection = (
            self.selection.model_dump()
            if isinstance(self.selection, RoutingSelection)
            else self.selection
        )
        return ProviderResult(
            structured=selection,
            usage=self.usage,
            accepted=self.accepted,
        )


def validate_provider_contract(
    provider: ModelProvider,
    *,
    structured_output: StructuredOutputRequest,
) -> None:
    """Validate provider support before issuing a structured request.

    Raises:
        UnsupportedProviderCapabilityError: If native structured output is
            unavailable.
        ValueError: If the required JSON schema is empty.
    """
    if not provider.capabilities.structured_output:
        raise UnsupportedProviderCapabilityError(
            "Provider does not support required native structured output"
        )
    if not structured_output.json_schema:
        raise ValueError("Structured output schema cannot be empty")


def parse_routing_selection(result: ProviderResult) -> RoutingSelection:
    """Validate and return structured routing output.

    Raises:
        MalformedStructuredOutputError: If a structured output is absent or does
            not satisfy: class:`RoutingSelection`.
    """
    if result.structured is None:
        raise MalformedStructuredOutputError("Provider returned no structured routing output")
    try:
        return RoutingSelection.model_validate(result.structured)
    except ValidationError as error:
        raise MalformedStructuredOutputError(
            "Provider returned malformed structured routing output"
        ) from error


async def complete_with_retries(
    provider: ModelProvider,
    messages: Sequence[ChatMessage],
    *,
    options: GenerationOptions,
    structured_output: StructuredOutputRequest,
) -> ProviderResult:
    """Complete a provider request under timeout and safe-retry rules.

    Retryable provider failures and timeouts are retried only before a request
    is known to have been accepted. Provider capability validation occurs
    before the first request.

    Args:
        provider: Resolved provider client.
        messages: Provider-neutral conversation messages.
        options: Generation, timeout, and retry settings.
        structured_output: Required native structured-output contract.

    Returns:
        The normalized provider result.

    Raises:
        UnsupportedProviderCapabilityError: If structured output is unsupported.
        ProviderTimeoutError: If all permitted attempts time out.
        ProviderError: If a provider failure is not safely retryable or retries
            are exhausted.
    """
    validate_provider_contract(provider, structured_output=structured_output)
    attempts = options.retries + 1
    for attempt in range(attempts):
        try:
            completion = provider.complete(
                messages,
                options=options,
                structured_output=structured_output,
            )
            if options.timeout is not None:
                return await asyncio.wait_for(completion, options.timeout)
            return await completion
        except TimeoutError as error:
            timeout_error = ProviderTimeoutError()
            if attempt == attempts - 1:
                raise timeout_error from error
            await asyncio.sleep(0)
        except ProviderError as error:
            if not error.retryable or error.accepted or attempt == attempts - 1:
                raise
            await asyncio.sleep(0)
    raise AssertionError("unreachable")
