"""Provider-neutral model contracts and deterministic routing helpers."""

from __future__ import annotations

import asyncio
import math
import time
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from typing import Annotated, Any, Literal, Protocol, TypeAlias

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    TypeAdapter,
    ValidationError,
    field_validator,
)


class ChatMessage(BaseModel):
    """Provider-neutral chat message sent to a model client.

    Attributes:
        role: Conversation role understood by the provider adapter.
        content: Text content for the message.
    """

    role: str
    content: str


class GenerationOptions(BaseModel):
    """Validated generation settings passed to a provider for one call.

    Attributes:
        model: Provider-native model identifier from the resolved registration.
        temperature: Sampling temperature.
        max_tokens: Optional positive output-token limit.
        timeout: Optional positive timeout in seconds for each attempt.
        retries: Number of safe retry attempts after the initial request.
    """

    model: str
    temperature: float = 0.0
    max_tokens: int | None = Field(default=None, gt=0)
    timeout: float | None = Field(default=None, gt=0)
    retries: int = Field(default=0, ge=0)


@dataclass(frozen=True)
class StructuredOutputRequest:
    """Named JSON schema that a provider must satisfy natively."""

    name: str
    schema: dict[str, Any]

    def __init__(
        self,
        name: str,
        schema: dict[str, Any] | None = None,
        *,
        json_schema: dict[str, Any] | None = None,
    ) -> None:
        resolved_schema = schema if schema is not None else json_schema
        if resolved_schema is None:
            raise ValueError("StructuredOutputRequest requires 'schema' or 'json_schema'")
        object.__setattr__(self, "name", name)
        object.__setattr__(self, "schema", resolved_schema)

    @property
    def json_schema(self) -> dict[str, Any]:
        """Return the native JSON schema for this structured-output request.

        Returns:
            The unconstrained serialized schema definition for the request.
        """
        return self.schema


class Usage(BaseModel):
    """Provider-neutral token usage counters.

    Attributes:
        input_tokens: Tokens consumed by request input.
        output_tokens: Tokens generated by the provider.
        total_tokens: Total tokens reported for the request.
    """

    input_tokens: int = Field(default=0, ge=0)
    output_tokens: int = Field(default=0, ge=0)
    total_tokens: int = Field(default=0, ge=0)
    cost: float = Field(default=0.0, ge=0)

    @field_validator("cost")
    @classmethod
    def validate_cost(cls, value: float) -> float:
        """Reject non-finite provider cost values."""
        if not math.isfinite(value):
            raise ValueError("cost must be finite")
        return value


class TerminalModelDecision(BaseModel):
    """The sole terminal response permitted for one model decision turn."""

    model_config = ConfigDict(extra="forbid")

    type: Literal["terminal"]
    response: dict[str, Any]


class ToolCallModelDecision(BaseModel):
    """The sole tool call permitted for one model decision turn."""

    model_config = ConfigDict(extra="forbid")

    type: Literal["tool_call"]
    call_id: str = Field(min_length=1)
    tool_id: str = Field(min_length=1)
    arguments: dict[str, Any]


ModelDecision: TypeAlias = Annotated[
    TerminalModelDecision | ToolCallModelDecision,
    Field(discriminator="type"),
]
_MODEL_DECISION_ADAPTER: TypeAdapter[ModelDecision] = TypeAdapter(ModelDecision)


@dataclass(frozen=True, slots=True)
class ToolResultMessage:
    """One bounded result from a prior tool call supplied to the next turn."""

    call_id: str
    status: str
    result: dict[str, Any]


@dataclass(frozen=True, slots=True)
class FakeModelRequest:
    """Safe observation of one request issued to :class:`FakeModel`."""

    message_roles: tuple[str, ...]
    options: GenerationOptions
    structured_output: StructuredOutputRequest
    tools: tuple[Mapping[str, Any], ...] = ()
    tool_results: tuple[ToolResultMessage, ...] = ()
    effective_deadline: float | None = None


class ProviderResult(BaseModel):
    """Normalized completion result returned by a model provider.

    Attributes:
        content: Optional unstructured text response.
        structured: Optional decoded structured response.
        usage: Provider-neutral usage counters.
        accepted: Whether the provider accepted the request. Accepted failures
            are not automatically retried.
        request_id: Optional non-secret provider request identifier.
    """

    content: str | None = None
    structured: dict[str, Any] | None = None
    usage: Usage = Field(default_factory=Usage)
    accepted: bool = False
    request_id: str | None = None


@dataclass(frozen=True, slots=True)
class ProviderCapabilities:
    """Capabilities advertised by a registered provider client.

    Attributes:
        structured_output: Supports native schema-constrained output.
        tool_calling: Supports provider-native tool calls.
        context_limit: Maximum advertised context size, or zero when unknown.
        usage_reporting: Returns token usage with results.
    """

    structured_output: bool = False
    tool_calling: bool = False
    context_limit: int = 0
    usage_reporting: bool = False


class ProviderError(RuntimeError):
    """Base provider error with explicit retry and acceptance state."""

    def __init__(
        self,
        message: str,
        *,
        retryable: bool = False,
        accepted: bool = False,
    ) -> None:
        super().__init__(message)
        self.retryable = retryable and not accepted
        self.accepted = accepted


class ProviderAuthenticationError(ProviderError):
    """Provider rejected or could not get authentication."""


class ProviderRateLimitError(ProviderError):
    """Provider rejected a request because the rate limit was exceeded."""

    def __init__(
        self,
        message: str = "Provider rate limit exceeded",
        *,
        accepted: bool = False,
    ) -> None:
        super().__init__(message, retryable=True, accepted=accepted)


class ProviderContentPolicyError(ProviderError):
    """Provider rejected content under its safety or usage policy."""


class ProviderTimeoutError(ProviderError):
    """Provider request exceeded the allowed timeout window."""

    def __init__(
        self,
        message: str = "Provider request timed out",
        *,
        accepted: bool = False,
    ) -> None:
        super().__init__(message, retryable=True, accepted=accepted)


class UnsupportedProviderCapabilityError(ProviderError):
    """Provider cannot satisfy a capability required by the request."""


class MalformedStructuredOutputError(ProviderError):
    """Provider output did not satisfy the required structured contract."""


class ModelProvider(Protocol):
    """Protocol implemented by credential-bearing model clients.

    Implementations are registered with a runtime-owned provider registry.
    Agents and run requests reference them indirectly and never retain their
    credentials or provider-specific configuration.
    """

    capabilities: ProviderCapabilities

    async def complete(
        self,
        messages: Sequence[ChatMessage],
        *,
        options: GenerationOptions,
        structured_output: StructuredOutputRequest,
        tools: Sequence[Mapping[str, Any]] = (),
        tool_results: Sequence[ToolResultMessage] = (),
        effective_deadline: float | None = None,
    ) -> ProviderResult:
        """Generate a completion for a provider-neutral chat request.

        Args:
            messages: Conversation history to send to the provider.
            options: Generation controls for model temperature, token caps, and
                retries.
            structured_output: Native JSON schema required for structured output.
            tools: Provider-neutral tools available for this turn.
            tool_results: Bounded results from prior provider-issued tool calls.
            effective_deadline: Optional monotonic deadline that bounds this call.

        Returns:
            Normalized provider response content, metadata, and usage counters.
        """


def build_routing_schema(
    routing_metadata: Sequence[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Return the constrained selection schema used for model routing."""
    schema = RoutingSelection.model_json_schema()
    if routing_metadata is not None:
        branches: list[dict[str, Any]] = []
        for entry in routing_metadata:
            agent_id = entry.get("name")
            if not agent_id:
                continue
            capability_ids = sorted(
                {
                    str(capability_id)
                    for capability in entry.get("capabilities", [])
                    for capability_id in (
                        capability.get("id"),
                        capability.get("name"),
                    )
                    if capability_id
                }
            )
            if not capability_ids:
                continue
            branches.append(
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "agent_id": {"const": str(agent_id)},
                        "capability_id": {"enum": capability_ids},
                        "arguments": {"type": "object"},
                    },
                    "required": ["agent_id", "capability_id"],
                }
            )
        schema = {"oneOf": branches}
    return schema


class RoutingSelection(BaseModel):
    """Strict structured capability selection accepted by the orchestrator.

    Attributes:
        agent_id: Published identifier of the selected agent.
        capability_id: Capability name or generated skill identifier.
        arguments: Structured arguments for the selected capability.
    """

    model_config = ConfigDict(extra="forbid")
    agent_id: str = Field(min_length=1)
    capability_id: str = Field(min_length=1)
    arguments: dict[str, Any] = Field(default_factory=dict)


class ModelConfiguration(BaseModel):
    """Immutable provider-neutral model configuration.

    The configuration identifies a provider and its provider model name, plus
    safe request defaults. Credentials, authorization headers, and other
    sensitive provider settings must remain inside the registered client.
    """

    provider: str = Field(min_length=1)
    model: str = Field(min_length=1)
    endpoint: str | None = None
    timeout: float = Field(default=30.0, gt=0)
    retries: int = Field(default=0, ge=0)

    model_config = ConfigDict(extra="forbid", frozen=True)


class FakeModel:
    """Deterministic provider for unit and acceptance tests."""

    capabilities = ProviderCapabilities(
        structured_output=True,
        tool_calling=True,
        context_limit=128_000,
        usage_reporting=True,
    )

    def __init__(
        self,
        selection: RoutingSelection | dict[str, Any] | str | Sequence[object] | None = None,
        *,
        usage: Usage | None = None,
        accepted: bool = True,
        script: Sequence[object] | None = None,
    ) -> None:
        if script is not None and selection is not None:
            raise ValueError("FakeModel accepts either selection or script, not both")
        selected_script = script
        if (
            selected_script is None
            and isinstance(selection, Sequence)
            and not isinstance(selection, str)
        ):
            selected_script = selection
        if selection is None and selected_script is None:
            raise ValueError("FakeModel requires a selection or script")
        self.selection = selection
        self._script = tuple(selected_script) if selected_script is not None else None
        self.usage = usage or Usage()
        self.accepted = accepted
        self.calls = 0
        self.requests: list[FakeModelRequest] = []

    async def complete(
        self,
        messages: Sequence[ChatMessage],
        *,
        options: GenerationOptions,
        structured_output: StructuredOutputRequest,
        tools: Sequence[Mapping[str, Any]] = (),
        tool_results: Sequence[ToolResultMessage] = (),
        effective_deadline: float | None = None,
    ) -> ProviderResult:
        """Return the configured fake completion payload.

        Args:
            messages: Conversation history supplied to the fake provider.
            options: Generation settings observed for the request.
            structured_output: Requested structured output contract.
            tools: Provider-neutral tool definitions for this turn.
            tool_results: Prior tool results for this turn.
            effective_deadline: Effective monotonic deadline for this turn.

        Returns:
            The synthetic provider result configured when the fake provider was created.
        """
        self.calls += 1
        self.requests.append(
            FakeModelRequest(
                message_roles=tuple(message.role for message in messages),
                options=options,
                structured_output=structured_output,
                tools=tuple(dict(tool) for tool in tools),
                tool_results=tuple(tool_results),
                effective_deadline=effective_deadline,
            )
        )
        selection: object
        if self._script is None:
            selection = self.selection
        elif self.calls <= len(self._script):
            selection = self._script[self.calls - 1]
        else:
            raise ProviderError("FakeModel script exhausted")
        if isinstance(selection, ProviderError):
            raise selection
        if isinstance(selection, ProviderResult):
            return selection
        if isinstance(selection, str):
            return ProviderResult(content=selection, usage=self.usage, accepted=self.accepted)
        payload = selection.model_dump() if isinstance(selection, BaseModel) else selection
        if not isinstance(payload, dict):
            raise TypeError("FakeModel script entries must be model results or dictionaries")
        return ProviderResult(structured=payload, usage=self.usage, accepted=self.accepted)


def build_model_decision_schema(
    response_type: type[BaseModel],
) -> StructuredOutputRequest:
    """Build the strict terminal-or-single-tool-call contract for a turn."""
    response_schema = response_type.model_json_schema()
    definitions = response_schema.pop("$defs", None)
    schema = {
        "oneOf": [
            {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "type": {"const": "terminal"},
                    "response": response_schema,
                },
                "required": ["type", "response"],
            },
            {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "type": {"const": "tool_call"},
                    "call_id": {"type": "string", "minLength": 1},
                    "tool_id": {"type": "string", "minLength": 1},
                    "arguments": {"type": "object"},
                },
                "required": ["type", "call_id", "tool_id", "arguments"],
            },
        ]
    }
    if definitions is not None:
        schema["$defs"] = definitions
    return StructuredOutputRequest(name="model_decision", schema=schema)


def parse_model_decision(
    result: ProviderResult,
    *,
    response_type: type[BaseModel],
) -> ModelDecision:
    """Parse exactly one strict terminal response or one strict tool call."""
    if not issubclass(response_type, BaseModel):
        raise TypeError("response_type must be a Pydantic model type")
    if result.structured is None:
        raise MalformedStructuredOutputError("Provider returned no structured model decision")
    try:
        decision = _MODEL_DECISION_ADAPTER.validate_python(result.structured)
        return decision
    except ValidationError as error:
        raise MalformedStructuredOutputError(
            "Provider returned malformed structured model decision"
        ) from error


def validate_provider_contract(
    provider: ModelProvider,
    *,
    structured_output: StructuredOutputRequest,
    tools: Sequence[Mapping[str, Any]] = (),
    tool_results: Sequence[ToolResultMessage] = (),
) -> None:
    """Validate provider support before issuing a structured request.

    Raises:
        UnsupportedProviderCapabilityError: If native structured output is
            unavailable.
        ValueError: If the required JSON schema is empty.
    """
    if not provider.capabilities.structured_output:
        raise UnsupportedProviderCapabilityError(
            "Provider does not support required native structured output"
        )
    if not structured_output.json_schema:
        raise ValueError("Structured output schema cannot be empty")
    if (tools or tool_results) and not provider.capabilities.tool_calling:
        raise UnsupportedProviderCapabilityError(
            "Provider does not support required native tool calling"
        )


def parse_routing_selection(result: ProviderResult) -> RoutingSelection:
    """Validate and return structured routing output.

    Raises:
        MalformedStructuredOutputError: If a structured output is absent or does
            not satisfy: class:`RoutingSelection`.
    """
    if result.structured is None:
        raise MalformedStructuredOutputError("Provider returned no structured routing output")
    try:
        return RoutingSelection.model_validate(result.structured)
    except ValidationError as error:
        raise MalformedStructuredOutputError(
            "Provider returned malformed structured routing output"
        ) from error


async def complete_with_retries(
    provider: ModelProvider,
    messages: Sequence[ChatMessage],
    *,
    options: GenerationOptions,
    structured_output: StructuredOutputRequest,
    deadline: float | None = None,
    tools: Sequence[Mapping[str, Any]] = (),
    tool_results: Sequence[ToolResultMessage] = (),
    effective_deadline: float | None = None,
    clock: Callable[[], float] = time.monotonic,
) -> ProviderResult:
    """Complete a provider request under timeout and safe-retry rules.

    Retryable provider failures and timeouts are retried only before a request
    is known to have been accepted. Provider capability validation occurs
    before the first request.

    Args:
        provider: Resolved provider client.
        messages: Provider-neutral conversation messages.
        options: Generation, timeout, and retry settings.
        structured_output: Required native structured-output contract.
        deadline: Optional monotonic deadline governing the whole request.
        tools: Provider-neutral tools available for this request.
        tool_results: Bounded results from prior tool calls.
        effective_deadline: Optional tighter monotonic deadline.
        clock: Monotonic clock used for deterministic deadline enforcement.

    Returns:
        The normalized provider result.

    Raises:
        UnsupportedProviderCapabilityError: If structured output is unsupported.
        ProviderTimeoutError: If all permitted attempts time out.
        ProviderError: If a provider failure is not safely retryable or retries
            are exhausted.
    """
    tool_aware = bool(tools) or bool(tool_results)
    if effective_deadline is not None:
        deadline = min(deadline, effective_deadline) if deadline is not None else effective_deadline
    validate_provider_contract(
        provider,
        structured_output=structured_output,
        tools=tools,
        tool_results=tool_results,
    )
    attempts = options.retries + 1
    for attempt in range(attempts):
        try:
            timeout_for_attempt: float | None = None
            if deadline is not None:
                remaining = deadline - clock()
                if remaining <= 0:
                    raise TimeoutError("Run deadline exceeded")
                timeout_for_attempt = remaining
            if options.timeout is not None:
                timeout_for_attempt = (
                    min(options.timeout, timeout_for_attempt)
                    if timeout_for_attempt is not None
                    else options.timeout
                )
            request_kwargs: dict[str, Any] = {
                "options": options,
                "structured_output": structured_output,
            }
            if tool_aware:
                request_kwargs["tools"] = tools
                request_kwargs["tool_results"] = tool_results
            if tool_aware or effective_deadline is not None:
                request_kwargs["effective_deadline"] = deadline
            completion = provider.complete(messages, **request_kwargs)
            if timeout_for_attempt is not None:
                return await asyncio.wait_for(completion, timeout_for_attempt)
            return await completion
        except TimeoutError as error:
            timeout_error = ProviderTimeoutError()
            if attempt == attempts - 1 or (deadline is not None and deadline <= clock()):
                raise timeout_error from error
            await asyncio.sleep(0)
        except ProviderError as error:
            if not error.retryable or error.accepted or attempt == attempts - 1:
                raise
            await asyncio.sleep(0)
    raise AssertionError("unreachable")
