"""Public transport-independent security contracts."""

from .approval import (
    ApprovalChallenge,
    ApprovalDecision,
    ApprovalState,
    ApprovalStore,
    Clock,
    IdentifierGenerator,
    InMemoryApprovalStore,
)
from .approval_token import (
    ApprovalReplayStore,
    ApprovalTokenClaims,
    ApprovalTokenService,
    ApprovalVerificationResult,
    InMemoryApprovalReplayStore,
)
from .context import AuthorizationContext, Principal
from .crypto import (
    ApprovalClock,
    ApprovalKeyResolver,
    ApprovalTokenSigner,
    ES256Signer,
    ES256Verifier,
    StaticApprovalKeyResolver,
)
from .errors import (
    ApprovalExpiredError,
    ApprovalRequiredError,
    ApprovalTokenBindingError,
    ApprovalTokenError,
    ApprovalTokenExpiredError,
    ApprovalTokenReplayError,
    ApprovalTokenRoleError,
    AuthorizationDeniedError,
    InsufficientScopeError,
    InvalidApprovalSignatureError,
    InvalidApprovalStateError,
    MalformedApprovalTokenError,
    MissingAuthorizationContextError,
    PolicyEvaluationError,
    PrematureApprovalTokenError,
    SecurityError,
    TaskCanceledError,
    UnknownApprovalKeyError,
    UnsupportedApprovalTokenError,
)
from .guardrails import (
    ApprovalRequirement,
    Guardrails,
    ScopeRequirement,
    discover_guardrails,
    get_guardrails,
    require_approval,
    require_scope,
)
from .pipeline import GuardrailResult, SecurityPipeline

__all__ = [
    "ApprovalChallenge",
    "ApprovalDecision",
    "ApprovalState",
    "ApprovalStore",
    "Clock",
    "IdentifierGenerator",
    "InMemoryApprovalStore",
    "ApprovalTokenClaims",
    "ApprovalTokenService",
    "ApprovalVerificationResult",
    "ApprovalReplayStore",
    "InMemoryApprovalReplayStore",
    "ApprovalClock",
    "ApprovalKeyResolver",
    "ApprovalTokenSigner",
    "ES256Signer",
    "ES256Verifier",
    "StaticApprovalKeyResolver",
    "AuthorizationContext",
    "Principal",
    "ApprovalRequirement",
    "Guardrails",
    "ScopeRequirement",
    "discover_guardrails",
    "get_guardrails",
    "require_approval",
    "require_scope",
    "GuardrailResult",
    "SecurityPipeline",
    "SecurityError",
    "MissingAuthorizationContextError",
    "InsufficientScopeError",
    "ApprovalRequiredError",
    "AuthorizationDeniedError",
    "ApprovalExpiredError",
    "TaskCanceledError",
    "InvalidApprovalStateError",
    "PolicyEvaluationError",
    "ApprovalTokenError",
    "MalformedApprovalTokenError",
    "UnsupportedApprovalTokenError",
    "UnknownApprovalKeyError",
    "InvalidApprovalSignatureError",
    "PrematureApprovalTokenError",
    "ApprovalTokenExpiredError",
    "ApprovalTokenBindingError",
    "ApprovalTokenRoleError",
    "ApprovalTokenReplayError",
]
